struct EnglishRoasts {
    static let all = [
        "You bring everyone so much joy—when you leave the room.",
        "You're like a cloud. When you disappear, it's a beautiful day.",
        "You’re the reason shampoo bottles have instructions.",
        "Your secrets are safe with me—I never listen to them anyway.",
        "You have something on your chin… no, the third one down.",
        "You’re like a campfire—loud, smoky, and best enjoyed from far away.",
        "Your brain is like a web browser with too many tabs open, and none of them are working.",
        "You’re like a sloth, but without the charm.",
        "You’re proof that not all who wander are lost… some are just clueless.",
        "Your voice is like nails on a chalkboard, but less helpful.",
        "You’d lose a debate with a rock.",
        "You bring nothing to the table except hunger.",
        "You couldn’t pour water out of a boot with instructions on the heel.",
        "You’re like a test nobody wants to take.",
        "Your handshake feels like meeting a wet napkin.",
        "You’re the human version of buffering.",
        "Your jokes are like math problems—confusing and not funny.",
        "If I had a penny for your thoughts, I’d still be broke.",
        "You’re proof that even evolution can hit the snooze button.",
        "You’re like a door that only squeaks—unnecessary and annoying.",
        "Your arguments are like expired coupons—useless.",
        "You’d trip over a wireless connection.",
        "You have something in common with Mondays: everyone hates you.",
        "You’re as sharp as a butter knife.",
        "You’re like a QR code that doesn’t scan—pointless.",
        "Your personality is like watching paint dry, but less colorful.",
        "You’re the kind of person who claps when the plane lands.",
        "You’d lose hide-and-seek in an empty room.",
        "You’re like a glow stick—completely useless until someone breaks you.",
        "Your best feature is your ability to leave the room.",
        "You’re like a Wi-Fi signal that keeps dropping—frustrating and unreliable.",
        "Your memory is as reliable as a Snapchat streak.",
        "Your sense of humor is like a dead battery—completely draining.",
        "You’re the reason stress balls were invented.",
        "You’re like a book nobody finishes reading.",
        "You’re as essential as a third wheel on a bicycle.",
        "You’re like an umbrella on a sunny day—out of place and unnecessary.",
        "You have the charm of a parking ticket.",
        "Your energy is like a dead flashlight—dim and barely there.",
        "You’re like a pizza without cheese—sad and incomplete.",
        "You couldn’t solve a Rubik’s Cube even if it came with instructions.",
        "You’re like a sandwich without bread—completely falling apart.",
        "You’re the human equivalent of a typo.",
        "Your ideas are as original as a rerun.",
        "You’d argue with a mirror just to lose.",
        "You’re the definition of a low battery warning.",
        "You’re as dependable as an umbrella in a hurricane.",
        "You’re like a shadow—always there but never helpful.",
        "You’d lose at solitaire.",
        "You’re like a clock with no hands—completely useless.",
        "You’re the kind of person who gets lost in a parking lot.",
        "You’d trip over a flat surface.",
        "You’re as predictable as a plot twist in a bad movie.",
        "You’re like an expired coupon—completely worthless.",
        "Your brain is on airplane mode.",
        "You have all the warmth of an ice cube.",
        "You’re like a vending machine that’s out of order—no one expects anything from you.",
        "You’re the human version of a mosquito.",
        "You’d fail a personality test.",
        "Your arguments are like a house of cards—easy to knock down.",
        "You’re as refreshing as lukewarm water.",
        "You’re like a puzzle missing half the pieces.",
        "You’re like a pop quiz—nobody asked for you, and nobody likes you.",
        "Your personality is like a blank canvas—uninspiring and empty.",
        "You’re like a cat video without the cat—pointless.",
        "You’re as useful as a paper umbrella in the rain.",
        "Your life is like a sitcom, but without the laughs.",
        "You’re like an elevator that never arrives—just a lot of waiting for nothing.",
        "You’re like a paperclip—always bending under pressure.",
        "You’d lose a race against a snail.",
        "You’re like a broken pencil—completely pointless.",
        "Your presence is like a typo in a professional email—awkward and unnecessary.",
        "You’re as functional as a phone with no signal.",
        "Your charm is as fake as a $3 bill.",
        "You’re like a speed bump—just slowing everyone down.",
        "You’re like a solar panel at night—completely useless.",
        "You’re the human version of a buffering wheel.",
        "Your personality is like decaf coffee—nobody wants it.",
        "You’re like a dictionary without definitions—confusing and pointless.",
        "You’re as forgettable as yesterday’s weather report.",
        "You’re the kind of person who gets a participation trophy and still complains.",
        "Your sense of direction is as bad as your sense of humor.",
        "You’re like a fire alarm that doesn’t work—unreliable and dangerous.",
        "You’re like a meme from 2012—outdated and irrelevant.",
        "You’re the human version of a dead-end street.",
        "Your comebacks are like boomerangs—they never come back.",
        "You’re like a commercial break—everyone’s waiting for you to end.",
        "Your sense of humor is like a brick wall—completely lifeless.",
        "You’re like a map with no directions—utterly useless.",
        "You’re like a sock without its pair—completely unnecessary.",
        "You’d lose an argument with an empty chair.",
        "You’re as sharp as a beach ball.",
        "You’re like a candle in a windstorm—flickering and eventually gone.",
        "Your personality is like an unsharpened pencil—dull and ineffective.",
        "You’re the human version of spam email.",
        "You’re like a question nobody wants to answer.",
        "Your life is like a loading screen—going nowhere fast.",
        "You’re like a vending machine that eats money—frustrating and pointless.",
        "You’re like a ceiling fan—constantly spinning but not really going anywhere."
    ]
}
