import Foundation

struct Roasts {
    static let all: [String] = [
            "Sei così inutile che una palla di neve in estate sarebbe più utile.",
            "La tua faccia ha un'espressione che mi fa venire il mal di testa.",
            "Spero che la tua vita vada come la tua carriera.",
            "Ci sono più speranze di salvezza per un pesce in una padella.",
            "La tua personalità è come un libro vuoto.",
            "L'unica cosa che hai in comune con un genio è la somiglianza con un oggetto immobile.",
            "Sei talmente fastidioso che persino le zanzare ti evitano.",
            "Non sono sicuro se sei stupido o semplicemente imbarazzante.",
            "Un pallone gonfiato ha più contenuto di te.",
            "Mi piacerebbe essere gentile, ma non posso quando parli.",
            "Avrei voluto che avessi più cervello... Ma non è mai troppo tardi.",
            "Sei l'esempio perfetto di ciò che non fare in vita.",
            "Non c'è niente di peggio di stare con te. Ah, sì, forse solo stare con un muro.",
            "Sei una risata involontaria.",
            "Il tuo livello di intelligenza è sotto il livello del mare.",
            "Per favore, non parlare mai più.",
            "Sei l'equivalente umano di una valigia mal fatta.",
            "Potresti essere un genio, se solo avessi avuto il coraggio di usare il cervello.",
            "Il tuo senso dell'umorismo è come un puzzle senza pezzi.",
            "C'è più vita in un cimitero che nei tuoi discorsi.",
            "Tutti possono essere qualcosa, tranne te.",
            "Potresti scomparire e nessuno noterebbe.",
            "La tua presenza è come una nuvola grigia.",
            "Ogni volta che parli, il mio cervello implora di silenzio.",
            "Hai una faccia che farebbe morire di vergogna una statua.",
            "Dovresti essere più utile se fossi un oggetto inanimato.",
            "Un po' di cortesia non ti farebbe male, ma capisco che è chiedere troppo.",
            "L'intelligenza ti ha fatto visita solo una volta e l'hai rifiutata.",
            "La tua risata è contagiosa… ma solo per il modo sbagliato.",
            "Sei la definizione di una battuta stantia.",
            "Sei l'unica persona che può far arrabbiare una pietra.",
            "Ogni parola che dici abbassa il livello medio di intelligenza.",
            "Potresti perdere una gara contro una lumaca.",
            "Spero che tu non abbia mai bisogno di un'opinione sensata.",
            "Sei un vero capolavoro... di disorganizzazione.",
            "Non so cosa sia peggio, il tuo stile o la tua opinione.",
            "Il tuo aspetto è come un puzzle incompleto.",
            "Sei come un lampione spento in una notte buia.",
            "Le tue battute sono talmente lente che potrebbero andare in vacanza.",
            "La tua testa è così vuota che potresti usarla come una scatola di scarpe.",
            "Mi fai pensare che il silenzio sia la risposta migliore.",
            "Sei la dimostrazione vivente che l'evoluzione non è sempre utile.",
            "Spero che tu non abbia intenzione di spiegarmi niente.",
            "Le tue idee sono così noiose che potrebbero far addormentare una pietra.",
            "Ogni volta che pensi, un angelo perde le sue ali.",
            "Il tuo livello di imbarazzo è più alto del mio rispetto.",
            "La tua personalità è come un telefono spento.",
            "Mai incontrato qualcuno che sapesse essere così irritante.",
            "Hai la capacità di rendere la noia un'arte.",
            "La tua intelligenza è come un miraggio.",
            "Sei l'unico a cui la realtà si rifiuta di adattarsi.",
            "La tua voce ha il potere di far spegnere i televisori.",
            "C'è più energia in una pila scarica che nelle tue idee.",
            "A volte mi chiedo come fai a essere tanto mediocre.",
            "La tua vita sociale è come una stanza vuota.",
            "Le tue parole hanno lo stesso impatto di un battito di ciglia.",
            "Sei come una nuvola di fumo che scompare in un istante.",
            "Non posso credere che esisti davvero.",
            "Non c'è niente di interessante in te, neanche il tuo volto.",
            "Siamo onesti, anche un muro sarebbe un miglior compagno di conversazione.",
            "Ogni volta che parli, perdo un po' di speranza nell'umanità.",
            "Sei il tipo di persona che fa venir voglia di leggere un libro.",
            "La tua opinione è così irrilevante che nessuno la nota.",
            "Sei la combinazione perfetta tra una pianta senza foglie e un pesce fuori dall'acqua.",
            "Potresti scomparire e la gente probabilmente non se ne accorgerebbe.",
            "Spero che tu non abbia mai bisogno di una conversazione intelligente.",
            "Sei la riprova che l'intelligenza non è distribuita in modo equo.",
            "La tua faccia è un buon motivo per indossare occhiali da sole.",
            "Sei l'unica persona che può farti torto da solo.",
            "Il mondo è un posto migliore quando non ci sei.",
            "La tua voce è l'unica cosa che mi fa rimpiangere il silenzio.",
            "Non ti preoccupare, sei troppo insignificante per farmi arrabbiare.",
            "La tua esistenza è come un errore di stampa.",
            "Spero che tu non pensi mai di diventare famoso.",
            "Sei talmente noioso che anche un libro di storia sarebbe più interessante.",
            "Il tuo sorriso è la cosa meno affascinante che ho mai visto.",
            "Il tuo livello di sensibilità è pari a quello di una roccia.",
            "Ci sono voluti millenni per creare la bellezza, e tu sei la prova che può essere distrutta in un istante.",
            "Sei l'incarnazione del perché a volte il silenzio è d'oro.",
            "Ogni volta che penso a te, mi chiedo che cosa è andato storto nella vita.",
            "Le tue battute non fanno ridere neanche un robot.",
            "Sei l'unico a cui è riuscito di essere completamente dimenticabile.",
            "La tua presenza è come una mosca in una stanza pulita.",
            "Ogni volta che vedo il tuo viso, capisco cos'è la vera noia.",
            "Non hai mai visto una battuta veramente divertente, vero?",
            "Le tue idee sono talmente vuote che potrei usarle per conservare le patatine.",
            "Non hai alcuna personalità, solo una copia sbiadita.",
            "Ogni volta che parli, sento un vuoto dentro di me.",
            "Sei l'equivalente umano di una borsa senza contenuto.",
            "La tua tristezza è più interessante del tuo sorriso.",
            "La tua mente è una prigione senza via d'uscita.",
            "Mi chiedo se tu sia davvero consapevole della tua mancanza di talento.",
            "La tua personalità è talmente piatta che potrei metterci sopra un bicchiere d'acqua.",
            "Ogni volta che guardo la tua faccia, mi chiedo cosa ci sia di sbagliato nel mondo.",
            "Le tue parole sono come l'acqua che scivola via.",
            "Potresti rendere noioso anche il miglior film.",
            "La tua assenza sarebbe una benedizione per il mondo.",
            "Non ti accorgi mai che stai facendo del male, ma continui comunque.",
            "Sei la persona di cui nessuno vuole parlare.",
            "Il tuo obiettivo dovrebbe essere rimanere in silenzio più spesso.",
            "Le tue risposte sono sempre le stesse, noiose e senza senso.",
            "La tua vita sociale è come un'immagine in bianco e nero.",
            "Ogni volta che fai una battuta, la gente si sente come se stesse per essere sepolta.",
            "Mi piacerebbe essere gentile, ma non posso quando vedo te.",
            "Sei un caso perso, ma non è mai troppo tardi per sparire.",
            "Non mi interessa mai sapere cosa pensi.",
            "Sei come un ostacolo nella mia giornata.",
            "Non so cosa sia più noioso, stare con te o guardare la vernice asciugare.",
            "La tua opinione è talmente inutile che non vale nemmeno la pena di ascoltarla.",
            "Sei talmente insignificante che un cane ti ignorerebbe.",
            "Sei la ragione per cui il silenzio è d'oro.",
            "Ogni volta che parli, è come se stessi lanciando pietre in un lago calmo.",
            "La tua presenza è come un errore che tutti sperano di dimenticare.",
            "Spero che tu impari a stare in silenzio.",
            "Sei la rappresentazione di tutto ciò che va storto in una giornata.",
            "Le tue opinioni sono come carta straccia.",
            "Ogni volta che ti guardo, mi sento più intelligente.",
            "Non so se sei triste o semplicemente sempre arrabbiato.",
            "La tua mancanza di carisma è una vera arte.",
            "Ogni volta che parli, non posso fare a meno di pensare a come faresti meglio a tacere.",
            "Sei la ragione per cui molti scelgono di stare da soli.",
            "Le tue idee sono così inafferrabili che nessuno se ne preoccupa.",
            "La tua mancanza di creatività è così evidente che dovrebbe essere illegale.",
            "Ogni volta che vedo la tua faccia, mi chiedo se esiste davvero qualcosa di peggio.",
            "La tua intelligenza è così bassa che potresti vivere senza un cervello.",
            "Non so se sei triste o semplicemente noioso.",
            "La tua faccia è la risposta a tutte le domande sbagliate.",
            "Sei come un vuoto che non si riesce a riempire.",
            "La tua esistenza è come una notte senza stelle.",
            "Non c'è mai niente di interessante da dire quando sei nella stanza.",
            "Sei un buon esempio di come non affrontare la vita.",
            "Non credo che qualcuno possa darti qualche buon consiglio.",
            "Ogni volta che parli, la gente desidera fuggire."
    ]
    
}

